export const ADD_CATEGORY_REQUEST  = "ADD_CATEGORY_REQUEST"
export const ADD_CATEGORY_SUCCESS  = "ADD_CATEGORY_SUCCESS"
export const ADD_CATEGORY_FAILURE  = "ADD_CATEGORY_FAILURE"
export const SHOW_CATEGORY_SUCCESS  = "SHOW_CATEGORY_SUCCESS"

export const DELETE_CATEGORY_SUCCESS = "DELETE_CATEGORY_SUCCESS"
export const DELETE_CATEGORY_FAILURE = "DELETE_CATEGORY_FAILURE"

export const SHOW_BRAND_SUCCESS = "SHOW_BRAND_SUCCESS"

export const ADMIN_ADD_PRODUCT_SUCCESS = "ADMIN_ADD_PRODUCT_SUCCESS"
export const ADMIN_ADD_PRODUCT_FAILURE = "ADMIN_ADD_PRODUCT_FAILURE"
export const ADMIN_ADD_PRODUCT_REQUEST = "ADMIN_ADD_PRODUCT_REQUEST"






